#!/bin/bash

if [ -z "${NEW_RELIC_INSTALL}" ] || [ ! "${NEW_RELIC_INSTALL}" == "true" ]; then
    echo "New Relic Install Skipped"
    # Remove new relic default files
    rm -rf /etc/services.d/newrelic
    rm -rf /etc/php7/conf.d/newrelic.ini
    exit;
fi

export NR_INSTALL_SILENT=true
export NR_INSTALL_KEY="${NEW_RELIC_INSTALL_KEY}"

# Update New Relic INI
ini=/etc/php7/conf.d/newrelic.ini

if [ ! -z "${APP_NAME}" ]; then
    sed -i "s/.*newrelic.appname =.*/newrelic.appname = \"${APP_NAME}\"/g" ${ini}
fi

if [ ! -z "${FRAMEWORK}" ]; then
    sed -i "s/.*newrelic.framework =.*/newrelic.framework = \"${FRAMEWORK}\"/g" ${ini}
fi

# Install new relic
newrelic-install install